### ISSUE TITLE
Nail down exactly what validation rules are required by Zcash

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/ed25519-zebra#1]
Ed25519 signatures are used in Zcash in JoinSplit signatures, described in this section of the protocol spec: https://zips.z.cash/protocol/protocol.pdf#concretejssig

However, the spec is not totally clear on what the exact validation rules are.  Writing a signature as `(R,s)` and a public key as `A`:

1. The spec says that
    > A valid Ed25519 public key (`A`) is defined as a point of order `l` on the Ed25519 curve

    but it's unclear whether this is what was meant. Checking that `A` is exactly of order `l` is quite expensive (and uncommon); was this supposed to say that `A` is of order at least `l`?

2. Ed25519 allows implementors to choose one of two checks (with or without cofactor multiplication) but the spec does not say which check is supposed to be used.

**Comment by hdevalence** [comment]
Note re 1): https://github.com/ZcashFoundation/ed25519-zebra/blob/e5be01580e980d75f774b4847df077bb7a035154/src/public_key.rs#L45-L48

**Comment by hdevalence** [comment]
Note re 2): https://github.com/ZcashFoundation/ed25519-zebra/blob/e5be01580e980d75f774b4847df077bb7a035154/src/public_key.rs#L126-L129

**Comment by hdevalence** [comment]
Xref: https://github.com/zcash/zips/issues/167

**Comment by hdevalence** [comment]
Per @ebfull, the JoinSplits are verified in `zcashd` via a call to `libsodium` here: https://github.com/zcash/zcash/blob/master/src/main.cpp#L875

Looking at `libsodium` 1.0.15, it appears the verification check is done here: https://github.com/jedisct1/libsodium/blob/c5e43f4c1cf62b4669b1f33516fc33ef2d005187/src/libsodium/crypto_sign/ed25519/ref10/open.c#L151

This does not multiply by the cofactor, so it seems the answer to (2) is that there is no cofactor multiplication.

For (1), it appears that the public key validation is done here: https://github.com/jedisct1/libsodium/blob/c5e43f4c1cf62b4669b1f33516fc33ef2d005187/src/libsodium/crypto_sign/ed25519/ref10/open.c#L135-L143

There are no comments so I don't know exactly what this was *intended* to do, but it seems like it attempts to decode the public key to a point and explicitly rejects the point encoded as `[0u8; 32]`.  This is a different validation check than both what the Zcash spec says (exact order `l`) and what I assumed was intended (order at least `l`).

**Comment by daira** [comment]
Exact order ℓ was intended (for the Zcash spec) but never implemented. We will change the spec to match the libsodium 1.0.15 implementation.
