### ISSUE TITLE
Breaking change curve25519-dalek

### ISSUE THREAD

**Issue by bgallois** [ZcashFoundation/ed25519-zebra#115]
The PR (https://github.com/dalek-cryptography/curve25519-dalek/pull/619) introduced a breaking change from version 4.1.1 to 4.1.2, with the 4.1.2 version only compatible with the latest nightly.

The unpinned version https://github.com/ZcashFoundation/ed25519-zebra/blob/c39bd4364a03f4b8eb97c21b9aa6c9b357074280/Cargo.toml#L21 is causing issues for downstream projects using older nightly versions. It would be beneficial to enforce a specific version to prevent this problem in the future, even if breaking changes are introduced only incrementing the maintenance release number.

**Comment by bgallois** [comment]
Sorry, but I misjudged the problem. I was thinking of not actually pinning the dependency, but rather replacing `version = ">= 4.0, < 4.2"` with `version = "4.1.2"` (or the latest version of the dependency at release time). However, since the breaking change occurs with a patch version increment, it will still be the same issue.

In fact, it is not possible because we rely on one repository that depends on ed25519-zebra (5 more that depend on curve25519-dalek ), which are now incompatible with old nightlies. Additionally, the same repository has another dependency with a version that is not compatible with the latest nightly, so we are stuck (more so if the second dependency receives a patch that changes the major version number).

**Comment by conradoplg** [comment]
Got it, thanks for reporting it. We were also hit by this issue in one of our projects :frowning_face:
