### ISSUE TITLE
VerificationKey Eq/Ord traits

### ISSUE THREAD

**Issue by melatron** [ZcashFoundation/ed25519-zebra#41]
Is there a reason why `VerificationKey` doesn't implement the Eq, Ord, PartialEq, PartialOrd traits? I can create a PR with adding this functionality if it is okay?

**Comment by teor2345** [comment]
I'm not sure, that might be a question for @dconnolly.

It's possible that we prefer constant-time equality checks for cryptographic code.

What's the use case for `Ord`?

**Comment by melatron** [comment]
I need an ordered set of public keys for a specific use case on a protocol.

**Comment by dconnolly** [comment]
> I need an ordered set of public keys for a specific use case on a protocol.

Check out the traits impl'd on `VerificationKeyBytes`, which has `Ord` and `PartialOrd` derived.

**Comment by melatron** [comment]
Yes, that is why I was wondering why are they not also derived for the VerificationKey. Aren't two VerificationKeys equal if their A_bytes are equal?
