### ISSUE TITLE
Benchmark image is dead

### ISSUE THREAD

**Issue by archseer** [ZcashFoundation/ed25519-zebra#59]
[coalesced-batch-graph.png](https://www.zfnd.org/images/coalesced-batch-graph.png) doesn't resolve anymore.

**Comment by conradoplg** [comment]
It's back up, thank you for reporting this and thanks @winniendela for fixing the link!

**Comment by archseer** [comment]
Hmm are you sure? I still can't open the page and I don't see any commits updating the image URL.

**Comment by conradoplg** [comment]
> Hmm are you sure? I still can't open the page and I don't see any commits updating the image URL.

It was fixed on the website, it got broken again, but now it's fixed again :sweat_smile: Thanks for letting us know!
