### ISSUE TITLE
Tag a new  ed25519-zebra release

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/ed25519-zebra#79]
## Motivation

We've made a number of changes to this crate since the last release (over 6 months ago) and have been requested to cut a new release to pick up the latest changes.

**Comment by daira** [comment]
A release would be nice because it would remove our duplicate `sha2` 0.9/0.10 dependency, as well as being necessary to fix #6638.

**Comment by mpguerra** [comment]
@dconnolly is this something that you could do?

**Comment by conradoplg** [comment]
I can make the release

**Comment by dconnolly** [comment]
Done https://crates.io/crates/ed25519-zebra/4.0.0
