### ISSUE TITLE
Add AsRef<[u8]> for Signature

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/ed25519-zebra#9]
Currently the Signature type splits data over two arrays to work around Serde length array restrictions. Implementing `AsRef<[u8]>` requires changing this, which requires a different workaround for Serde.

**Comment by conradoplg** [comment]
[No longer needed](https://github.com/ZcashFoundation/ed25519-zebra/pull/46#issuecomment-1457424319)
